# Generated by Django 2.2.13 on 2020-07-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdxNewslettersSuscribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscribed', models.BooleanField(default=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
            ],
        ),
    ]
